name: Deploy to Staging 

on:
  push:
    branches: [ "feature/VSP-1192-Implement-CI-Server" ]
  pull_request:
    branches:
      - "develop" 
    paths:
      - ".github/workflows/deployStaging.yaml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Update Bundler
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: '2.6.8'
          bundler-cache: true
    - name: Run Fastlane Firebase
      env:
          GMP_KEY: ${{ secrets.GMP_KEY }}
          AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
          AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
          PUBLISHABLE_KEY: ${{ secrets.PUBLISHABLE_KEY }}
      run: bundler exec fastlane firebase
