# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Make a new debug build"
  lane :build do
    gradle(task: "clean assembleStagingDebug")
  end

  desc "Submit a new Beta Build to Firebase"
  lane :firebase do
    gradle(task: "clean bundleStagingRelease")
    firebase_app_distribution(
      app: "1:1071143441498:android:75fd393c7bb8ea75dd7463",
      android_artifact_type: "AAB"
      )
  end

  desc "Submit a new Beta Build to Playstore"
  lane :beta do
    gradle(task: "clean bundleStagingRelease")
    upload_to_play_store(
      track: 'beta',
      skip_upload_apk: true
      )
  end
end
